### ISSUE TITLE
Download jar seems to be empty

### ISSUE THREAD

**Issue by DiamondIceNS** [Headline22/CleverBotAPI-Java#1]
I've added the Maven installation to my project with Gradle and it seems to have downloaded and compiled the dependency, but it's empty.  The only files within are pom.properties, pom.xml, and manifest.mf.

![capture](https://cloud.githubusercontent.com/assets/10872887/22858309/fd498c66-f07e-11e6-8d13-f2a5e41184fc.PNG)

The downloadable jar from the project page also has this issue.

**Comment by Headline22** [comment]
Working on it now.

**Comment by DiamondIceNS** [comment]
Thanks for the quick response back.  I see the project is relatively new so of course there will be some early setup mistakes.

**Comment by Headline22** [comment]
Can you confirm that this jar [here](https://oss.sonatype.org/content/repositories/commichaelwflaherty-1009/com/michaelwflaherty/cleverbotapi/1.0.1/cleverbotapi-1.0.1.jar) works?

**Comment by DiamondIceNS** [comment]
I'm not really sure how to import local jars into my project, still a real low level beginner with using dependencies, but looking at the jar file I can at least see the classes this time.

**Comment by Headline22** [comment]
Alrighty. Maven should update within the next few hrs as I've just released v1.0.1.

**Comment by DiamondIceNS** [comment]
I imagine that would mean the Version for Maven should be 1.0.1-RELEASE, then?

**Comment by Headline22** [comment]
"1.0.1" will be the new maven version number. New updates will no longer have -RELEASE appended.

**Comment by DiamondIceNS** [comment]
Works perfectly now! Thanks!
